name: "hello everyone"

on:
  push:
    branches: ["master"] 

jobs:
  deploy-1stClass: 
    runs-on: windows-latest
    steps:
      uses: actions/checkout@v4
      - run: echo "Pull de code"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: "Publicar versi√≥n"
